apiVersion: builtin
kind: PatchTransformer
metadata:
  name: add-fsgroup-consul-only
patch: |-
  - op: add
    path: /spec/template/spec/securityContext/fsGroup
    value: 1001
  - op: add
    path: /spec/template/spec/securityContext/fsGroupChangePolicy
    value: OnRootMismatch
target:
  kind: StatefulSet
  name: sas-consul-server
