apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-saswork
  namespace: sas-viya
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-csi-sc
